### ISSUE TITLE
Регистрация пользователя

### ISSUE THREAD

**Issue by gryroach** [gryroach/theater-auth-service#3]
- переписать сохранение пользователя при регистрации через репозиторий
- реализовать создание записи в Redis в версией токена в виде `session_version[user_id] = 1`

Оценка: 5

**Comment by KirillYarkov** [comment]
Создам репозиторий через generic на основе кода из gist

https://gist.github.com/gryroach/b39986602f618ad2ceca42e7e4ea9dac
