### ISSUE TITLE
Выход из всех устройств

### ISSUE THREAD

**Issue by gryroach** [gryroach/theater-auth-service#7]
- реализовать ручку выхода из всех устройств
- изменить версию токена для пользователя в Redis 
- ~~выдать пользователю новые токены с новой версией~~

Оценка: 13

**Comment by KirillYarkov** [comment]
@gryroach Может быть не выдавать автоматом пользователю новые токены с новой версией? Типа логика "выйти со всех, кроме текущей" или "выйти со всех"? Я бы добавил выйти со всех, а кроме текущей оставил на случай запроса фьюче реквеста

**Comment by gryroach** [comment]
> @gryroach Может быть не выдавать автоматом пользователю новые токены с новой версией? Типа логика "выйти со всех, кроме текущей" или "выйти со всех"? Я бы добавил выйти со всех, а кроме текущей оставил на случай запроса фьюче реквеста

Давай. Это логично и упростит задачу

**Comment by KirillYarkov** [comment]
Так, а эту будем считать закрытой?
